export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_CREATED = "USER_CREATED";
export const USER_ALREADY_CREATED = "USER_ALREADY_CREATED";
export const USER_FAILED_LOGIN = "USER_FAILED_LOGIN";
export const USER_SUCESS_LOGIN = "USER_SUCESS_LOGIN";
export const LOGOUT = "LOGOUT";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const UPLOADING_FILE = "UPLOADING_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_DENIED = "UPLOAD_FILE_DENIED";
export const CREATE_LINK_SUCCESS = "CREATE_LINK_SUCCESS";
export const CREATE_LINK_DENIED = "CREATE_LINK_DENIED";
