export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_CREATED = "USER_CREATED";
export const USER_ALREADY_CREATED = "USER_ALREADY_CREATED";
export const CLEAN_ALERT = "CLEAN_ALERT";
