export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_CREATED = "USER_CREATED";
export const USER_ALREADY_CREATED = "USER_ALREADY_CREATED";
export const USER_FAILED_LOGIN = "USER_FAILED_LOGIN";
export const USER_SUCESS_LOGIN = "USER_SUCESS_LOGIN";
export const CLEAN_ALERT = "CLEAN_ALERT";
export const LOGOUT = "LOGOUT";
